### ISSUE TITLE
Homebrew/actions/setup-homebrew@master - Issue

### ISSUE THREAD

**Issue by bruuuuuuuce** [Homebrew/actions#240]
I am facing an issue with the `setup-homebrew` action. When I use the action using os `macos-latest`, I am not able to brew install anything. Here is an example github action file
```
name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
       - name: Set up Homebrew
         id: set-up-homebrew
         uses: Homebrew/actions/setup-homebrew@master

      - name: Install Homebrew Bundler RubyGems
        run: brew install-bundler-gems

      - run: brew install rust
```
^^^ this action is failing for me at the `brew install rust` step, saying `No available formula or cask with the name "rust"`. 

However, if I edit my action file to be
```
name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Homebrew Bundler RubyGems
        run: brew install-bundler-gems

      - run: brew install rust
```
`brew install rust` works just fine. 

This is an issue for me because I am creating a brew formula. The formula depends on `rust`, and the default workflows created by `brew tap-new` include this action, which is causing my bottling to fail because it can't find a brew formula named `rust`.
