### ISSUE TITLE
Changes in #324 break our actions/setup-homebrew deployment

### ISSUE THREAD

**Issue by ryantimjohn** [Homebrew/actions#330]
Hi @Bo98 , I've read the changes in #324 , and it seems the way this change:

> Adjust token behaviour to use HTTP headers rather than URL authentication.
> This matches how actions/checkout behaves.

Changed how token authentication works broke the actions ability to clone a repo in the setup-homebrew action.

This is the error we're getting:
```
fatal: could not read Username for 'https://github.com/': No such device or address
```

Our setup has not changed since the last time we ran a test-bot workflow, here's what our invocation looks like:
```
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }} 
```

Please let me know if there's any additional environmental variables we have to set up to get this working. Cheers!
