### ISSUE TITLE
Do not recommend using actions from `master`

### ISSUE THREAD

**Issue by IanVS** [Homebrew/actions#677]
It is best practice to pin actions to a specific SHA, to avoid security vulnerabilities like https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised.  

Documentation should be updated to avoid recommending `@master`, and instead recommend pinning against a SHA, and using a tool like renovatebot or dependabot to handle upgrades.

**Comment by p-linnane** [comment]
Our workflows use `@master` for ease of maintenance across our repos. Every other Action we use across our repos is pinned. Users are naturally free to set their workflows up how they prefer.

We're going to keep the documentation as is, and allow users to make their own choices.

**Comment by IanVS** [comment]
> and allow users to make their own choices

To be clear, I wasn't suggesting to take away any choice from users, but rather to give them better information and an increased choice. I think it's irresponsible to recommend an insecure method of installing your actions.  It seems you disagree about that, and that's your prerogative, but it's disappointing. I hope your actions are never compromised, or else you may have some difficult explaining to do.

**Comment by MikeMcQuaid** [comment]
> To be clear, I wasn't suggesting to take away any choice from users, but rather to give them better information and an increased choice.

What specifically do you think we should be saying? What text should be in the documentation that actually works for users?

> I hope your actions are never compromised, or else you may have some difficult explaining to do.

If you can provide some specifics on what may cause our actions to be compromised then we'll work on that.

**Comment by IanVS** [comment]
>If you can provide some specifics on what may cause our actions to be compromised then we'll work on that.

I don't have specifics, but the last time I checked, tj-actions didn't know how their credentials were leaked either.  I believe good security practice is to 1) try to not get compromised and 2) limit the impact if you ever are.  

> What specifically do you think we should be saying?

Here is an example of what you could say:

```md
# Setup Homebrew Github Action

An action that sets up a Homebrew environment.

Runs on `ubuntu` and `macos`.

## Usage

```yaml
- name: Set up Homebrew
  id: set-up-homebrew
  uses: Homebrew/actions/setup-homebrew@<SHA of latest commit>
```

Note: it is recommended to pin all GitHub actions to a commit SHA, as a form of dependency management.  If you would rather not periodically review and update the SHA, you can use `Homebrew/actions/setup-homebrew@master` instead, which will always run the latest code from this repository.  [Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot) can also help automate the process of updating your actions.

### Caching ruby gems

This action also sets up the variables necessary to cache the gems installed by Homebrew developer commands (e.g. `brew style`). To use these add:

```yaml
- name: Cache Homebrew Bundler RubyGems
  id: cache
  uses: actions/cache@v3
  with:
    path: ${{ steps.set-up-homebrew.outputs.gems-path }}
    key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
    restore-keys: ${{ runner.os }}-rubygems-

- name: Install Homebrew Bundler RubyGems
  if: steps.cache.outputs.cache-hit != 'true'
  run: brew install-bundler-gems
```

Note you do not need to use the `actions/setup-ruby` or `actions/checkout` steps because this action will install the necessary Ruby for Homebrew and checkout the repository being tested.

```
